name: E2E Testing with Cypress
on: push
jobs:
  test:
    name: Install and Run Tests
    runs-on: ubuntu-18.04
    steps:
      - name: Install Cypress
        run: yarn add cypress --dev
      - name: run tests
        run: yarn cypress run --record --key CYPRESS_RECORD_KEY
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        # Recommended: pass the GitHub token lets this action correctly
        # determine the unique run id necessary to re-run the checks
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}